server:
  port: 8989
spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 1000MB
      max-file-size: 1000MB
      file-size-threshold: 0
  redis:
    host: 127.0.0.1
    port: 6379
  mvc:
    throw-exception-if-no-handler-found: true

